version: '3.7'
services:
  mysql:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: standard
      MYSQL_USER: standard
      MYSQL_PASSWORD: standard
    networks:
      - backend

  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   ports:
  #     - '27017:27017'
  #   networks:
  #     - backend

  api:
    build: .
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - '3333:3333'
    volumes:
      - ./:/usr/src/app

volumes:
  db_data:

networks:
  backend:
